name: islami_app_new
description: Islami App - Flutter frontend
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  http: ^1.4.0
  file_picker: ^10.2.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  provider: ^6.1.5
  share_plus: ^11.0.0
  video_player: ^2.10.0
  youtube_player_iframe: ^5.2.1
  youtube_player_flutter: ^9.1.1
  geolocator: ^14.0.2
  flutter_tts: ^4.0.2
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.0
  android_intent_plus: ^4.0.3
  flutter_compass: ^0.8.1
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/turkey_cities.json
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-Italic.ttf
          style: italic
        - asset: fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic
