services:
  - type: web
    name: islami-app-backend
    runtime: python
    rootDir: backend
    region: oregon
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_URL
        value: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
      - key: DATABASE_URL
        fromDatabase:
          name: islami-app-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: islami-app-db
    plan: basic-1gb
    diskSizeGB: 10
    region: oregon